global:
  image:
    registry: docker.io

controller:
  image:
    image: mahdixak/ingress-nginx-controller   # your pushed controller image
    tag: v1.14.3
    digest: ""                                 # clear digest so it won’t force the original

  admissionWebhooks:
    patch:
      image:
        repository: docker.io/mahdixak/ingress-nginx-kube-webhook-certgen
        tag: v1.6.7
        digest: ""                             # clear original digest
        pullPolicy: Always